### ISSUE TITLE
Cyclic behaviour 

### ISSUE THREAD

**Issue by FrancisBanville** [BIO6032/2019_replication_HastingsPowell_1991#13]
Only keep t = 5000-10000 for Figure2D and Figure5. These time steps are the one kept by H&P, and uniquely represent the cyclic behavior of the mode.

**Comment by gabrieldansereau** [comment]
Re-reading the original article, I'm not exactly sure H&P did that for Figures 2D and 5 specifically. I've tried, and it doesn't change the interpretation of the figures (Figure 2D is pretty much the same, Figure 5 has even less points). I'll leave as it is for now.

**Comment by tpoisot** [comment]
Works for me, if the results match, trust the results and not the text
