### ISSUE TITLE
Submit to ReScience

### ISSUE THREAD

**Issue by aammd** [BIO6032/2019_replication_HastingsPowell_1991#16]
https://github.com/ReScience/submissions

The procedure for submitting a replication seems pretty straightforward. You already have a beautiful pdf, which satisfies the first requirement. 
The second is a simple YAML document that describes the metadata (template provided at that link). 
The final step seems to be simply opening an issue and providing links to the necessary material. If you open the link above and click the "submit" link (or simply open a new issue) you will see an issue template that you can fill out. 

I'm here to support you all if you need!

**Comment by tpoisot** [comment]
Marking this one as closed since @­gabrieldansereau is about to submit - fantastic job everyone
