### ISSUE TITLE
Bifurcation diagram

### ISSUE THREAD

**Issue by tpoisot** [BIO6032/2019_replication_HastingsPowell_1991#17]
`PyDSTool` is no longer recommended, so if the `figure4_verification` file is still needed, it needs an update:

https://docs.juliadiffeq.org/stable/analysis/bifurcation/#

**Comment by gabrieldansereau** [comment]
It's not needed anymore. I was looking at the oscillations of z for different values of b1 to see the difference in the primary and secondary local maxima (which we removed from the bifurcation diagrams). The part with `PyDSTool` was some tutorial I'd found for it, but I didn't have time to adapt it.

**Comment by tpoisot** [comment]
OK, so remove everything that is not required anymore, and then I'll finish the figures.

**Comment by gabrieldansereau** [comment]
I've cleaned the repo. Everything is required in the `figure2, figure3, figure4, figureS1` scripts. @FrancisBanville, could you check the `figure5` one? I think it depends if we want to keep [Figure 2d2](https://github.com/BIO6032/2019_replication_HastingsPowell_1991/blob/tim-edits/article/figures/fig2d2.png) (not necessary) and the [GIF](https://github.com/BIO6032/2019_replication_HastingsPowell_1991/blob/master/article/figures/teacup.tmp.gif) (it's cool, I'd keep it).
