### ISSUE TITLE
Flipped axis on 3D Teacup figure

### ISSUE THREAD

**Issue by gabrieldansereau** [BIO6032/2019_replication_HastingsPowell_1991#21]
Tagging @tpoisot 

I have a problem replicating the teacup figure (2D) in _Julia v1.3.1_.

The Y axis in flipped in the original paper. When I try to flip it using GR (with `yflip = true`), the axis labels are misplaced all over the plot. I've tested it and the problem occurs only with 3D figures.

I found a slightly ridiculous workaround, [which is to invert the values and invert the labels manually](https://github.com/BIO6032/2019_replication_HastingsPowell_1991/blob/e2b1d30d0904c5e1de4239289096c197b9ef3bd2/code/figure2D.jl#L31-42). I'm not sure if it's the best idea though. Otherwise, I have no problem using PyPlot, but I know installing it can be a pain sometimes.

What do you think is the best option? Invert values/labels or use PyPlot?
Should I post this to the Julia Discourse? 

#### Misplaced Labels
![Misplaced labels](https://raw.githubusercontent.com/BIO6032/2019_replication_HastingsPowell_1991/4f6039a13407c4fe7e2431cd2f437f471b7144ec/article/figures/fig2d_misplaced.png)
 
#### Inverted values
![Inverted values](https://raw.githubusercontent.com/BIO6032/2019_replication_HastingsPowell_1991/4f6039a13407c4fe7e2431cd2f437f471b7144ec/article/figures/fig2d.png)

#### PyPlot 
![pyplot](https://raw.githubusercontent.com/BIO6032/2019_replication_HastingsPowell_1991/4f6039a13407c4fe7e2431cd2f437f471b7144ec/article/figures/fig2d_pyplot.png)

**Comment by gabrieldansereau** [comment]
(@tpoisot  here) tagging @mkborregaard - can you flip the coordinates in a 3d plot?

**Comment by mkborregaard** [comment]
I think you should open an issue on Plots and tag jheinen (the developer of GR) - this is clearly just a bug.
I think both using the pyplot backend, and just flipping the ticks, are both perfectly fine as workarounds. IMHO pyplot is prettier for 3d.

**Comment by gabrieldansereau** [comment]
Ok, thanks for the tip!
