### ISSUE TITLE
Atom, GitHub and Julia resources 

### ISSUE THREAD

**Issue by FrancisBanville** [BIO6032/2019_replication_HastingsPowell_1991#3]
Here is an issue for sharing any pertinent resources (documents, cheat sheets, videos, _etc._) related to Atom, GitHub and Julia.

**Comment by FrancisBanville** [comment]
### Atom ###
This is a series of videos useful to get used to the text editor Atom: 
[Atom Editor Tutorials](https://www.youtube.com/watch?v=WWwBQQOGllo&index=1&list=PLYzJdSdNWNqwNWlxz7bvu-lOYR0CFWQ4I)

**Comment by ElodieBsq** [comment]
Here's a website that really helped me to understand how to push a file on GitHub from Atom. Really helpful!

https://www.hongkiat.com/blog/manage-git-github-atom/
